spring:
  application:
    name: toy-chat

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql-container
    username: root
    password: 1234

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true

  rabbitmq:
    host: localhost
    port: 61613
    username: guest
    password: guest